### ISSUE TITLE
Installing GLFW 3

### ISSUE THREAD

**Issue by Horkyze** [drahosp/ppgso#3]
U mna (Ubuntu 14.04 LTS) sa **neda** urobit:

`apt-get install libglfw3-dev`

Treba to asi skompilovat manualne podla http://www.glfw.org/docs/latest/compile.html
Po instalacii aj tak kompilovanie ppsgo vyhodilo error:

```
$ make
g++ -o gl_gradient -O2 -std=c++11 -Wextra -Wall gl_gradient.cpp -lm -lGLEW -lglfw -lGL -lGLU
/usr/bin/ld: cannot find -lglfw
collect2: error: ld returned 1 exit status
make: *** [gl_gradient] Error 1
```

Skusal som aj v MakeFile prepisat 
`-lglfw` na `-lglfw3`
Ale potom zase vyhodi: 

```
$ make
g++ -o gl_gradient -O2 -std=c++11 -Wextra -Wall gl_gradient.cpp -lm -lGLEW -lglfw3 -lGL -lGLU
/usr/bin/ld: //usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [gl_gradient] Error 1
```

Malo by to fungovat? Alebo je na mojej strane chyba?

**Comment by drahosp** [comment]
See install instructions in README of 4b8c044
